"use client";

import { useState, useEffect } from "react";
import { ethers } from "ethers";
import { getNFTContractAddress, getNFTContractABI, getBrowserProvider } from "@/app/bc/utils";

const STOCKS = ["S&P 500", "Wheat", "Apple"];

interface TransactionNFTData {
  id: string;
  proposalId: string;
  stockName: string;
  type: "BUY" | "SELL";
  rawAmount: string; // Przechowuje surową, sformatowaną wartość z kontraktu
  price: string;
  timestamp: string;
}

export default function BrokerPortfolioPage() {
  const [nfts, setNfts] = useState<TransactionNFTData[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState("");

  useEffect(() => {
    async function loadNFTs() {
      try {
        setLoading(true);
        setError("");

        const provider = await getBrowserProvider();
        const nftAddress = getNFTContractAddress();
        const nftAbi = getNFTContractABI();
        const nftContract = new ethers.Contract(nftAddress, nftAbi, provider);

        const signer = await provider.getSigner();
        const brokerEOA = await signer.getAddress();

        let tokenIds: bigint[] = [];
        try {
          tokenIds = await nftContract.getBrokerTransactions(brokerEOA);
        } catch (err) {
          const nextId: bigint = await nftContract.nextTransactionId();
          const ids: bigint[] = [];
          for (let i = 0; i < Number(nextId); i++) {
            try {
              const tx = await nftContract.getTransaction(i);
              if ((tx.broker as string).toLowerCase() === brokerEOA.toLowerCase()) {
                ids.push(BigInt(i));
              }
            } catch (e) {
            }
          }
          tokenIds = ids;
        }

        const fetchedNfts: TransactionNFTData[] = [];
        for (const id of tokenIds) {
          const txData = await nftContract.getTransaction(id);
          const propId = txData.proposalId ?? txData[0];
          const stockIndex = txData.stock ?? txData[1];
          const txType = txData.transactionType ?? txData[2];
          const amountVal = txData.amount ?? txData[3];
          const priceVal = txData.price ?? txData[4];
          const timeVal = txData.timestamp ?? txData[6];

          fetchedNfts.push({
            id: id.toString(),
            proposalId: propId.toString(),
            stockName: STOCKS[Number(stockIndex)] || `Unknown (${stockIndex})`,
            type: Number(txType) === 0 ? "BUY" : "SELL",
            rawAmount: ethers.formatEther(amountVal),
            price: ethers.formatEther(priceVal),
            timestamp: new Date(Number(timeVal) * 1000).toLocaleString()
          });
        }

        setNfts(fetchedNfts);
      } catch (err: any) {
        console.error("Error loading NFT portfolio:", err);
        setError(err.message || "Failed to fetch NFT data.");
      } finally {
        setLoading(false);
      }
    }

    loadNFTs();
  }, []);

  if (loading) return <div style={{ padding: "2rem", fontFamily: "sans-serif", textAlign: "center" }}>Querying DAO treasury for NFT certificates...</div>;
  if (error) return <div style={{ padding: "2rem", fontFamily: "sans-serif", color: "red", textAlign: "center" }}>Configuration or network error: {error}</div>;

  return (
    <div style={{ maxWidth: "900px", margin: "0 auto", padding: "2rem", fontFamily: "sans-serif" }}>
      <header style={{ borderBottom: "1px solid #ccc", paddingBottom: "1rem", marginBottom: "1rem" }}>
        <h1 style={{ margin: 0 }}>DAO Treasury — NFT Certificates</h1>
      </header>

      <p style={{ color: "#666", marginBottom: "1rem" }}>
        The items below represent immutable trade receipts generated by the Broker and held on-chain as ERC-721 tokens owned by the HedgeFundDAO.
      </p>

      {nfts.length === 0 ? (
        <div style={{ padding: "2rem", textAlign: "center", background: "#f9f9f9", borderRadius: "8px", border: "1px dashed #ccc" }}>
          <p style={{ color: "#444", margin: 0, fontWeight: "600" }}>DAO treasury is currently empty</p>
          <p style={{ color: "#999", fontSize: "0.9rem", marginTop: "0.5rem" }}>The Broker has not executed any orders via executeOrder() yet.</p>
        </div>
      ) : (
        <div style={{ display: "flex", flexDirection: "column", gap: "1rem" }}>
          {nfts.map((nft) => {
            const isBuy = nft.type === "BUY";
            const priceNum = Number(nft.price);
            const rawAmountNum = Number(nft.rawAmount);

            // Wyliczanie wartości zgodnie z logiką matematyczną kontraktu
            const unitsField = isBuy 
              ? (priceNum > 0 ? (rawAmountNum / priceNum).toFixed(4) : "0")
              : rawAmountNum.toFixed(4);

            const ethField = isBuy 
              ? rawAmountNum.toFixed(1)
              : (priceNum > 0 ? (rawAmountNum * priceNum).toFixed(1) : "0");

            return (
              <div key={nft.id} style={{ border: "1px solid #ddd", borderRadius: "8px", padding: "1rem", background: "#f9f9f9" }}>
                <div style={{ display: "flex", justifyContent: "space-between", alignItems: "center", marginBottom: "0.75rem" }}>
                  <strong style={{ fontSize: "1rem" }}>{nft.stockName}</strong>
                  <div style={{ background: isBuy ? "#0b66ff" : "#d63333", color: "white", padding: "0.25rem 0.5rem", borderRadius: "4px", fontSize: "0.8rem", fontWeight: "bold" }}>
                    {nft.type} ORDER
                  </div>
                </div>

                <div style={{ background: "white", padding: "0.75rem", borderRadius: "6px", marginBottom: "0.75rem", border: "1px solid #eee" }}>
                  <div style={{ display: "flex", justifyContent: "space-between", marginBottom: "0.4rem" }}>
                    <span style={{ color: "#666" }}>Token ID</span>
                    <span style={{ fontFamily: "monospace" }}>#{nft.id}</span>
                  </div>
                  
                  <div style={{ display: "flex", justifyContent: "space-between", marginBottom: "0.4rem" }}>
                    <span style={{ color: "#666" }}>DAO Proposal ID</span>
                    <span style={{ fontFamily: "monospace" }}>#{nft.proposalId}</span>
                  </div>
                  
                  <div style={{ display: "flex", justifyContent: "space-between", marginBottom: "0.4rem" }}>
                    <span style={{ color: "#666" }}>{isBuy ? "Acquired Volume" : "Liquidated Volume"}</span>
                    <span style={{ fontWeight: 600, color: isBuy ? "#00875a" : "#de350b" }}>{unitsField} Units</span>
                  </div>

                  <div style={{ display: "flex", justifyContent: "space-between", marginBottom: "0.4rem" }}>
                    <span style={{ color: "#666" }}>{isBuy ? "Total Cost" : "Total Revenue"}</span>
                    <span style={{ fontWeight: 600 }}>{ethField} ETH</span>
                  </div>
                  
                  <div style={{ display: "flex", justifyContent: "space-between"}}>
                    <span style={{ color: "#666" }}>Unit price</span>
                    <span style={{ fontWeight: 600, color: "#d97706" }}>{Number(nft.price).toFixed(1)} ETH</span>
                  </div>
                </div>
                <div style={{ marginTop: "0.6rem", color: "#666", fontSize: "0.85rem", textAlign: "right", borderTop: "1px dashed #eee", paddingTop: "0.4rem" }}>
                  <span style={{ fontFamily: "monospace" }}>{nft.timestamp}</span>
                </div>
              </div>
            );
          })}
        </div>
      )}
    </div>
  );
}